---
abstract: 'A mechanized-based programming API against redmine server.'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.83'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Redmine
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0.07
  HTML::WikiConverter: 0.68
  HTML::WikiConverter::Markdown: 0.05
  WWW::Mechanize: 1.52
  pQuery: 0.07
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: http://github.com/gugod/net-redmine
version: 0.03
